[build]
target = "avr-specs/avr-atmega328p.json"

[unstable]
build-std = ["core"]

[target.'cfg(target_arch = "avr")']
runner = "avrdude -p m328p -c arduino -P /dev/ttyACM1 -b 115200 -U flash:w:target/avr-atmega328p/debug/tetruino.elf"
